### ISSUE TITLE
Apfs

### ISSUE THREAD

**Issue by theCurseOfHackintosh** [CVFZ/ASRock-Z270-Gaming-K4-OpenCore-Hackintosh#1]
Setz Apfs Minversion und Mindate auf -1, dann sollte es ohne den driverloder funktionieren......
"ist" oder "isst" es installiert?!

**Comment by Fritzudco** [comment]
Zdravo franz
Du lass Mensch hier niemand dich mögen du trottel.
Putin <3
Ich hassen dich! Franz curse

Ich nicht hassen dich du was haben das GitHub Seite hier (czfv).

**Comment by theCurseOfHackintosh** [comment]
Was willst du von mir? @Fritzudco
Stalker oder was?
Ist nicht lustig was du machst, aber das wird deine eine, letzte, Gehirnzelle nicht verstehen. Wenn du einen gute. Arzt willst gibt es Google.
Oder hast du zuviel von dem Zeug genommen, wie du einmal den Username hattest und mich damit belästigt hast?!
